### ISSUE TITLE
How to access the module?

### ISSUE THREAD

**Issue by JayTheLordOfTheFishes** [Jeefrect/CamX#1]
Greetings, how is your mod used?

There are no keybinds in the readme, ive put the file in the 
![grafik](https://github.com/user-attachments/assets/b845fdad-b90f-4272-88ac-7e8c0cbf23e4)

Folder but its not in the Active Modules or anywhere?

How do i access it?
Thanks!

**Comment by Jeefrect** [comment]
Hello, you are trying to install the mod through Kinomod, which is incorrect. CamX is not associated with Kinomod. You need to place the .ksm file in the **mods** folder. _However, make sure that KSL is installed for the mod to work properly. Note that ZML is not supported._

**Please place the CameraX.ksm file in the Mods folder located in the game directory.**
The path typically looks like this: `CarX Drift Racing Online\kino\mods`
Correct path result: `CarX Drift Racing Online\kino\mods\CameraX.ksm`

**Comment by JayTheLordOfTheFishes** [comment]
ahh thank you very much!
